### ISSUE TITLE
How should it be with TypeScript?

### ISSUE THREAD

**Issue by ShiibaDev** [andrefelipe/vite-php-setup#14]
Hi, I am using Babel TypeScript. I am new on Vite so I don't understanding clearly how to work with this.

**Comment by andrefelipe** [comment]
Hello @ShiibaDev sorry I am very busy and will not be able to help. Please take a look at the Vite docs, it is very clean and easy to follow.
https://vitejs.dev/guide/
https://vitejs.dev/config/

**Comment by ShiibaDev** [comment]
Hi, I am sorry to bother, and thanks for the help.
