### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by k07n** [andrefelipe/vite-php-setup#5]
Hi!
Can you explain why this would happen, please?

![ws-error](https://user-images.githubusercontent.com/1233056/116047671-60cf6d80-a685-11eb-8f06-b1c853d708fe.png)

**Comment by andrefelipe** [comment]
Sorry I never used WebSockets with Vite yet.

**Comment by k07n** [comment]
Oh, so you have this error too (and infinite page refresh)? I've clone this repo, install, link assets and run, no other changes was made. ANY thoughts where I was missed something?

**Comment by k07n** [comment]
I've got this! 
hmr was connecting to "public host", but must to localhost, so server.hmr little configuration helps:
```
server {
    hmr: {
     port:3000,
     host: "localhost",
    }
}
```

ps: thx for your job, great php-setup ;)

**Comment by McSmog** [comment]
> ```
> server {
>     hmr: {
>      port:3000,
>      host: "localhost",
>     }
> }
> ```

I had an error until I added the protocol: 
```js
  server: {
    hmr: {
      port: 3000,
      protocol: 'ws',
      host: 'localhost',
    },
  },
```
thx k07n

**Comment by andrefelipe** [comment]
Hello @k07n sorry for not answering, I have been very busy.

Strange, I never had yet to change the "server.hmr" options. Don't know why yet. Have already done 5 projects with this kind of setup. Maybe something to do with the web server. I use Laravel Valet.

Thanks for looking into it!
