### ISSUE TITLE
npm run dev issue

### ISSUE THREAD

**Issue by Sensei85** [andrefelipe/vite-php-setup#8]
> my-php-project@0.0.0 dev C:\wamp64\www\vite-php-setup\vite
> APP_ENV=development vite

'APP_ENV' is not recognized as an internal or external command,
operable program or batch file.

Please help. Running npm run gives this issue. Great work by the way and is it possible to make it work with svelte instead of view

**Comment by andrefelipe** [comment]
That should be related to Windows. This may be your answer, check the comments too:
https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows

**Comment by Sensei85** [comment]
Thanks @andrefelipe , appreciate the help. Also is there a way we can make it work with svelte. So you can use svelte components instead of vue. And looks like it's only when the index file changes that the HMR kicks in, how about to watch for any file with ".php" change, and when saved HMR reloads the browser page for you. That would be neat. Thanks again for this repo, really helped me

**Comment by andrefelipe** [comment]
The PHP refresh is already set up with liveReload plugin. Please check the vite.config.js

For svelte should be simple take a look on Vite docs https://vitejs.dev and repo https://github.com/vitejs/vite

**Comment by Sensei85** [comment]
Thanks, will share a repo when I finally learn vite configs and get it to work with svelte.
